In [116]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


from bs4 import BeautifulSoup
from urllib import request



website = request.urlopen("https://www.pro-football-reference.com/years/2021/fantasy.htm").read()
soup = BeautifulSoup(website, 'lxml')

table = soup.find('table', attrs={'id': 'fantasy','class': 'per_match_toggle'})

table_headers = [header.text for header in table.find('thead').find_all('th')]
table_rows = table.find_all('tr')

player_data = [[td.getText() for tr in table_rows[i].findAll(['td','th'])] for i in table_rows]

print(table_headers)
df = pd.DataFrame(player_data,table_headers)

df.head()

df = pd.DataFrame(df, columns = table_headers)

In [117]:
# fantasy football datasets; results from each season

ff21 = pd.read_csv('https://raw.githubusercontent.com/fantasydatapros/data/master/yearly/2021.csv', index_col = 0)

ff20 = pd.read_csv('https://raw.githubusercontent.com/fantasydatapros/data/master/yearly/2020.csv')

ff19 = pd.read_csv('https://raw.githubusercontent.com/fantasydatapros/data/master/yearly/2019.csv', index_col = 0)


# team stats and rankings from each game per season

team19 = pd.read_csv("C:/Users/steph/OneDrive/Documents/Data Projects/2019_NFL_COMBINE.csv", index_col = 0)
team20 = pd.read_csv("C:/Users/steph/OneDrive/Documents/Data Projects/2020_NFL_COMBINE.csv", index_col = 0)
team21 = pd.read_csv("C:/Users/steph/OneDrive/Documents/Data Projects/2021_NFL_COMBINE.csv", index_col = 0)
team22 = pd.read_csv("C:/Users/steph/OneDrive/Documents/Data Projects/2022_NFL_COMBINE.csv", index_col = 0)

# Incoming rookie data



# PFF Data (OL rankings, etc)


# Injury Data?
# contract data? years in the league?

In [118]:
ff21.head()

,Player,Tm,Pos,Age,G,GS,Tgt,Rec,PassingYds,PassingTD,PassingAtt,RushingYds,RushingTD,RushingAtt,ReceivingYds,ReceivingTD,FantasyPoints,Int,Fumbles,FumblesLost
0,Jonathan Taylor*+,IND,RB,22,17,17,51.0,40.0,0.0,0.0,0.0,1811.0,18.0,332.0,360.0,2.0,333.0,0.0,4.0,2.0
1,Cooper Kupp*+,LAR,WR,28,17,17,191.0,145.0,0.0,0.0,1.0,18.0,0.0,4.0,1947.0,16.0,295.0,0.0,0.0,0.0
2,Deebo Samuel*+,SFO,WR,25,16,15,121.0,77.0,24.0,1.0,2.0,365.0,8.0,59.0,1405.0,6.0,262.0,0.0,4.0,2.0
3,Josh Allen,BUF,QB,25,17,17,0.0,0.0,4407.0,36.0,646.0,763.0,6.0,122.0,0.0,0.0,403.0,15.0,8.0,3.0
4,Austin Ekeler,LAC,RB,26,16,16,94.0,70.0,0.0,0.0,0.0,911.0,12.0,206.0,647.0,8.0,274.0,0.0,4.0,3.0

In [119]:
ff19.head()

,Player,Tm,Pos,Age,G,GS,Tgt,Rec,PassingYds,PassingTD,PassingAtt,RushingYds,RushingTD,RushingAtt,ReceivingYds,ReceivingTD,FantasyPoints,Int,Fumbles,FumblesLost
Unnamed: 0,,,,,,,,,,,,,,,,,,,,
0,Christian McCaffrey,CAR,RB,23.0,16.0,16.0,142.0,116.0,0.0,0.0,2.0,1387.0,15.0,287.0,1005.0,4.0,469.20,0.0,1.0,0.0
1,Lamar Jackson,BAL,QB,22.0,15.0,15.0,0.0,0.0,3127.0,36.0,401.0,1206.0,7.0,176.0,0.0,0.0,415.68,6.0,9.0,2.0
2,Derrick Henry,TEN,RB,25.0,15.0,15.0,24.0,18.0,0.0,0.0,0.0,1540.0,16.0,303.0,206.0,2.0,294.60,0.0,5.0,3.0
3,Aaron Jones,GNB,RB,25.0,16.0,16.0,68.0,49.0,0.0,0.0,0.0,1084.0,16.0,236.0,474.0,3.0,314.80,0.0,3.0,2.0
4,Ezekiel Elliott,DAL,RB,24.0,16.0,16.0,71.0,54.0,0.0,0.0,0.0,1357.0,12.0,301.0,420.0,2.0,311.70,0.0,3.0,2.0

In [120]:
team19.head()

,Week,Day,Date,Unnamed: 5,Opp,Tm,Opp.1,1stD,TotYd,PassY,...,TO,1stD.1,TotYd.1,PassY.1,RushY.1,TO.1,Offense,Defense,Sp. Tms,Home_team
0,1,Sun,8-Sep,W,Tampa Bay Buccaneers,31.0,17.0,17.0,256.0,158.0,...,2.0,21.0,295.0,174.0,121.0,4.0,-7.51,19.12,1.10,San Francisco 49ers
1,2,Sun,15-Sep,W,Cincinnati Bengals,41.0,17.0,27.0,571.0,312.0,...,1.0,14.0,316.0,291.0,25.0,1.0,27.34,1.14,-6.64,San Francisco 49ers
2,3,Sun,22-Sep,W,Pittsburgh Steelers,24.0,20.0,26.0,436.0,268.0,...,5.0,11.0,239.0,160.0,79.0,2.0,-3.72,10.20,0.12,San Francisco 49ers
3,4,NaN,NaN,NaN,Bye Week,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,San Francisco 49ers
4,5,Mon,7-Oct,W,Cleveland Browns,31.0,3.0,22.0,446.0,171.0,...,NaN,9.0,180.0,78.0,102.0,4.0,12.38,22.56,-10.50,San Francisco 49ers

Need to clean player name from *, + and/or both.

Need to group by position, as points scored and value is dependent on position.

need a dataset of predictor variables for final -- previous year's players (2021) plus rookies (2022) draft.

Need to bring in a dataset of rookies 

Need a dataset of team ranks from previous year (2021)

We'll use 19 and 20 as training years; 21 as test year. 

Final model will use previous 2 season data, and other, to predict upcoming season data

In [121]:
ff21.dtypes

ff20.dtypes

Player            object
Tm                object
Pos               object
Age                int64
G                  int64
GS                 int64
Tgt                int64
Rec                int64
PassingYds         int64
PassingTD          int64
PassingAtt         int64
RushingYds         int64
RushingTD          int64
RushingAtt         int64
ReceivingYds       int64
ReceivingTD        int64
FantasyPoints    float64
Int                int64
Fumbles            int64
FumblesLost        int64
dtype: object

In [122]:
# cleaning player names

ff21['Player'] = ff21['Player'].str.replace("+","", regex = True)
ff21['Player'] = ff21['Player'].str.replace("*","", regex = True)

ff20['Player'] = ff20['Player'].str.replace("+","", regex = True)
ff20['Player'] = ff20['Player'].str.replace("*","", regex = True)

ff19['Player'] = ff19['Player'].str.replace("+","", regex = True)
ff19['Player'] = ff19['Player'].str.replace("*","", regex = True)

Now, let's merge these dataframes on Player name

In [123]:
# concatenating data frames

ff_all = pd.merge(ff19, ff20, how = 'outer', left_on = ff19['Player'], right_on = ff20['Player'], suffixes = ('_19', '_20')).reset_index(drop = True)

ff_all.head()

,key_0,Player_19,Tm_19,Pos_19,Age_19,G_19,GS_19,Tgt_19,Rec_19,PassingYds_19,...,PassingAtt_20,RushingYds_20,RushingTD_20,RushingAtt_20,ReceivingYds_20,ReceivingTD_20,FantasyPoints_20,Int_20,Fumbles_20,FumblesLost_20
0,Christian McCaffrey,Christian McCaffrey,CAR,RB,23.0,16.0,16.0,142.0,116.0,0.0,...,0.0,225.0,5.0,59.0,149.0,1.0,73.0,0.0,0.0,0.0
1,Lamar Jackson,Lamar Jackson,BAL,QB,22.0,15.0,15.0,0.0,0.0,3127.0,...,376.0,1005.0,7.0,159.0,0.0,0.0,333.0,9.0,10.0,4.0
2,Derrick Henry,Derrick Henry,TEN,RB,25.0,15.0,15.0,24.0,18.0,0.0,...,0.0,2027.0,17.0,378.0,114.0,0.0,314.0,0.0,3.0,2.0
3,Aaron Jones,Aaron Jones,GNB,RB,25.0,16.0,16.0,68.0,49.0,0.0,...,0.0,1104.0,9.0,201.0,355.0,2.0,212.0,0.0,2.0,0.0
4,Ezekiel Elliott,Ezekiel Elliott,DAL,RB,24.0,16.0,16.0,71.0,54.0,0.0,...,0.0,979.0,6.0,244.0,338.0,2.0,172.0,0.0,6.0,5.0

In [124]:
# first, adding suffix to 21
ff21 = ff21.add_suffix('_21')

In [125]:
ff21.head()

,Player_21,Tm_21,Pos_21,Age_21,G_21,GS_21,Tgt_21,Rec_21,PassingYds_21,PassingTD_21,PassingAtt_21,RushingYds_21,RushingTD_21,RushingAtt_21,ReceivingYds_21,ReceivingTD_21,FantasyPoints_21,Int_21,Fumbles_21,FumblesLost_21
0,Jonathan Taylor,IND,RB,22,17,17,51.0,40.0,0.0,0.0,0.0,1811.0,18.0,332.0,360.0,2.0,333.0,0.0,4.0,2.0
1,Cooper Kupp,LAR,WR,28,17,17,191.0,145.0,0.0,0.0,1.0,18.0,0.0,4.0,1947.0,16.0,295.0,0.0,0.0,0.0
2,Deebo Samuel,SFO,WR,25,16,15,121.0,77.0,24.0,1.0,2.0,365.0,8.0,59.0,1405.0,6.0,262.0,0.0,4.0,2.0
3,Josh Allen,BUF,QB,25,17,17,0.0,0.0,4407.0,36.0,646.0,763.0,6.0,122.0,0.0,0.0,403.0,15.0,8.0,3.0
4,Austin Ekeler,LAC,RB,26,16,16,94.0,70.0,0.0,0.0,0.0,911.0,12.0,206.0,647.0,8.0,274.0,0.0,4.0,3.0

In [130]:
# concatenating data frames (19+20 with 21)

ff21['key_0'] = ff21['Player_21']


ff_all = ff_all.merge(ff21, on = 'key_0')

ff_all

,key_0,Player_19,Tm_19,Pos_19,Age_19,G_19,GS_19,Tgt_19,Rec_19,PassingYds_19,...,PassingAtt_21_y,RushingYds_21_y,RushingTD_21_y,RushingAtt_21_y,ReceivingYds_21_y,ReceivingTD_21_y,FantasyPoints_21_y,Int_21_y,Fumbles_21_y,FumblesLost_21_y
0,Christian McCaffrey,Christian McCaffrey,CAR,RB,23.0,16.0,16.0,142.0,116.0,0.0,...,0.0,442.0,1.0,99.0,343.0,1.0,91.0,0.0,1.0,0.0
1,Lamar Jackson,Lamar Jackson,BAL,QB,22.0,15.0,15.0,0.0,0.0,3127.0,...,382.0,767.0,2.0,133.0,0.0,0.0,240.0,13.0,6.0,3.0
2,Derrick Henry,Derrick Henry,TEN,RB,25.0,15.0,15.0,24.0,18.0,0.0,...,1.0,937.0,10.0,219.0,154.0,0.0,175.0,0.0,1.0,0.0
3,Aaron Jones,Aaron Jones,GNB,RB,25.0,16.0,16.0,68.0,49.0,0.0,...,0.0,799.0,4.0,171.0,391.0,6.0,177.0,0.0,2.0,1.0
4,Ezekiel Elliott,Ezekiel Elliott,DAL,RB,24.0,16.0,16.0,71.0,54.0,0.0,...,1.0,1002.0,10.0,237.0,287.0,2.0,205.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,Garrett Griffin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,39.0,0.0,4.0,0.0,1.0,0.0
529,Stanley Morgan Jr.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,3.0,0.0,1.0,11.0,0.0,1.0,0.0,0.0,0.0
530,Kevin Rader,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,8.0,0.0,1.0,0.0,0.0,0.0
531,Kevin White,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,38.0,0.0,4.0,0.0,0.0,0.0
532,Kendall Hinton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,175.0,1.0,24.0,0.0,0.0,0.0

In [132]:
# split up by position

ff_rb = ff_all.loc[ff_all['Pos_21_y'] == 'RB']
ff_wr = ff_all.loc[ff_all['Pos_21_y'] == 'WR']
ff_qb = ff_all.loc[ff_all['Pos_21_y'] == 'QB']
ff_te = ff_all.loc[ff_all['Pos_21_y'] == 'TE']

In [133]:
ff_rb.head()

,key_0,Player_19,Tm_19,Pos_19,Age_19,G_19,GS_19,Tgt_19,Rec_19,PassingYds_19,...,PassingAtt_21_y,RushingYds_21_y,RushingTD_21_y,RushingAtt_21_y,ReceivingYds_21_y,ReceivingTD_21_y,FantasyPoints_21_y,Int_21_y,Fumbles_21_y,FumblesLost_21_y
0,Christian McCaffrey,Christian McCaffrey,CAR,RB,23.0,16.0,16.0,142.0,116.0,0.0,...,0.0,442.0,1.0,99.0,343.0,1.0,91.0,0.0,1.0,0.0
2,Derrick Henry,Derrick Henry,TEN,RB,25.0,15.0,15.0,24.0,18.0,0.0,...,1.0,937.0,10.0,219.0,154.0,0.0,175.0,0.0,1.0,0.0
3,Aaron Jones,Aaron Jones,GNB,RB,25.0,16.0,16.0,68.0,49.0,0.0,...,0.0,799.0,4.0,171.0,391.0,6.0,177.0,0.0,2.0,1.0
4,Ezekiel Elliott,Ezekiel Elliott,DAL,RB,24.0,16.0,16.0,71.0,54.0,0.0,...,1.0,1002.0,10.0,237.0,287.0,2.0,205.0,0.0,1.0,1.0
5,Dalvin Cook,Dalvin Cook,MIN,RB,24.0,14.0,14.0,63.0,53.0,0.0,...,0.0,1159.0,6.0,249.0,224.0,0.0,172.0,0.0,3.0,2.0

Data is now separated by position; with stats from 2019, 2020, and 2021 all under each name.

Can we add more to these data frames, in terms of -- year in the league in '21, rookie contract or not, previous year team passing ranks, rushing ranks, qb play, OL play, etc.

In [135]:
ff_rb.corr()

,Age_19,G_19,GS_19,Tgt_19,Rec_19,PassingYds_19,PassingTD_19,PassingAtt_19,RushingYds_19,RushingTD_19,...,PassingAtt_21_y,RushingYds_21_y,RushingTD_21_y,RushingAtt_21_y,ReceivingYds_21_y,ReceivingTD_21_y,FantasyPoints_21_y,Int_21_y,Fumbles_21_y,FumblesLost_21_y
Age_19,1.000000,0.217195,0.167270,0.011133,0.007307,0.016916,NaN,-0.051477,-0.006858,0.045287,...,0.062944,-0.245645,-0.170309,-0.205957,-0.104673,-0.023268,-0.177918,-0.120565,-0.151950,-0.150400
G_19,0.217195,1.000000,0.348206,0.418970,0.398061,0.069291,NaN,0.077257,0.388706,0.296380,...,0.150213,0.156177,0.029628,0.159455,0.225442,0.164317,0.164028,0.080526,0.097110,-0.003893
GS_19,0.167270,0.348206,1.000000,0.598052,0.585318,-0.042160,NaN,0.043863,0.863479,0.731644,...,0.222580,0.501488,0.403273,0.528980,0.295380,0.241508,0.457773,0.056301,0.313313,0.265329
Tgt_19,0.011133,0.418970,0.598052,1.000000,0.994937,0.292315,NaN,0.309118,0.620228,0.495504,...,0.173754,0.425423,0.325296,0.437482,0.498273,0.415581,0.462845,0.025034,0.288530,0.193725
Rec_19,0.007307,0.398061,0.585318,0.994937,1.000000,0.292406,NaN,0.322060,0.603500,0.478138,...,0.150269,0.419095,0.333033,0.432381,0.498976,0.418820,0.463319,0.015199,0.279840,0.197131
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ReceivingTD_21_y,-0.023268,0.164317,0.241508,0.415581,0.418820,-0.002784,NaN,-0.010060,0.189394,0.146813,...,0.156984,0.460014,0.438296,0.494989,0.717936,1.000000,0.624076,-0.047933,0.406900,0.309741
FantasyPoints_21_y,-0.177918,0.164028,0.457773,0.462845,0.463319,-0.076304,NaN,-0.061106,0.536704,0.433629,...,0.335322,0.957108,0.909112,0.951483,0.798564,0.624076,1.000000,0.113147,0.669881,0.522864
Int_21_y,-0.120565,0.080526,0.056301,0.025034,0.015199,-0.016433,NaN,-0.017343,0.119241,0.083182,...,0.369406,0.130884,0.114194,0.166683,0.104305,-0.047933,0.113147,1.000000,0.014979,0.060968
Fumbles_21_y,-0.151950,0.097110,0.313313,0.288530,0.279840,-0.118254,NaN,-0.090646,0.362207,0.294933,...,0.098478,0.671318,0.611236,0.667592,0.542840,0.406900,0.669881,0.014979,1.000000,0.811984
FumblesLost_21_y,-0.150400,-0.003893,0.265329,0.193725,0.197131,-0.092241,NaN,-0.097349,0.281013,0.256611,...,-0.007010,0.551997,0.497830,0.559466,0.378647,0.309741,0.522864,0.060968,0.811984,1.000000

,Player,Tm,Pos,Age,G,GS,Tgt,Rec,PassingYds,PassingTD,PassingAtt,RushingYds,RushingTD,RushingAtt,ReceivingYds,ReceivingTD,FantasyPoints,Int,Fumbles,FumblesLost
0,Jonathan Taylor,IND,RB,22,17,17,51.0,40.0,0.0,0.0,0.0,1811.0,18.0,332.0,360.0,2.0,333.0,0.0,4.0,2.0
1,Cooper Kupp,LAR,WR,28,17,17,191.0,145.0,0.0,0.0,1.0,18.0,0.0,4.0,1947.0,16.0,295.0,0.0,0.0,0.0
2,Deebo Samuel,SFO,WR,25,16,15,121.0,77.0,24.0,1.0,2.0,365.0,8.0,59.0,1405.0,6.0,262.0,0.0,4.0,2.0
3,Josh Allen,BUF,QB,25,17,17,0.0,0.0,4407.0,36.0,646.0,763.0,6.0,122.0,0.0,0.0,403.0,15.0,8.0,3.0
4,Austin Ekeler,LAC,RB,26,16,16,94.0,70.0,0.0,0.0,0.0,911.0,12.0,206.0,647.0,8.0,274.0,0.0,4.0,3.0

# need a dataset of predictor variables for final 

from bs4 import BeautifulSoup
from urllib import request

# 2022 data or testing data

r = request.get("https://www.pro-football-reference.com/years/2022/fantasy.htm").read()
soup = BeautifulSoup(website, 'lxml')

table = soup.find('table', attrs={'id': 'fantasy','class': 'per_match_toggle'})

table_headers = [header.text for header in table.find('thead').find_all('th')]
table_rows = table.find_all('tr')

player_data = [[td.getText() for tr in table_rows[i].findAll(['td','th'])] for i in table_rows]

print(table_headers)
df = pd.DataFrame(player_data,table_headers)

df.head()